### ISSUE TITLE
Can you add thumbnails to buttons

### ISSUE THREAD

**Issue by chenpaner** [don1138/blender-qmm#2]
Thank you very much for making a nice plugin, but I'm not very familiar with English, can you please add a thumbnail icon to the material button！

**Comment by don1138** [comment]
There is sample code for making thumbnails like KitOps and Sanctus Library, but that would mean making a different kind of menu, and I like the smaller drop-down version I'm using. I could add 16px color chips, but they wouldn't be very readable.

I'm open to localizing the add-on into other languages, though.

Since you're in Shanghai, I was able to get the list translated into "Simple Chinese". If you're willing to pitch in and review it, and make any needed corrections, I'll add it in.

```
Noble Metals:        贵族金属。
  Gold                 黄金
  Gold Fresnel         菲涅尔金
  Palladium            钯金
  Platinum             铂金
  Silver               银
  Silver Fresnel       银菲涅尔

Base Metals:         基本金属。
  Aluminium            铝
  Copper               铜
  Copper Fresnel       铜菲涅尔
  Iron                 铁
  Lead                 铅
  Lead Rough           粗铅
  Tin                  锡
  Titanium Polished    钛 抛光
  Titanium Textured    钛的纹理
  Zinc                 锌

Alloys:              合金。
  Brass                黄铜
  Bronze               青铜
  Chrome               铬
  Steel                钢

Extras:              额外的。
  Asphalt              沥青
  Asphalt Bleached     漂白的沥青
  Cinnabar             朱砂
  Glass Hack           玻璃
  Mercury              水银
  Rubber Cutting Mat   橡胶切割垫
  Tinted Plaster       着色的石膏
  Wall Paint           墙面漆
```

**Comment by chenpaner** [comment]
Thank you very much for your reply, I rechecked the translation
Noble Metals:        贵金属
  Gold                 黄金
  Gold Fresnel         菲涅尔金
  Palladium            钯金
  Platinum             铂金
  Silver               银
  Silver Fresnel       菲涅尔银

Base Metals:         基础金属
  Aluminium            铝
  Copper               铜
  Copper Fresnel       菲涅尔铜
  Iron                 铁
  Lead                 铅
  Lead Rough           粗糙铅
  Tin                  锡
  Titanium Polished    抛光钛
  Titanium Textured    纹理钛
  Zinc                 锌

Alloys:              合金
  Brass                黄铜
  Bronze               青铜
  Chrome               铬
  Steel                钢

Extras:              额外的
  Asphalt              沥青
  Asphalt Bleached     白沥青
  Cinnabar             红金属
  Glass Hack           玻璃投影
  Mercury              水银
  Rubber Cutting Mat   橡胶切割垫
  Tinted Plaster       着色的石膏
  Wall Paint           墙面漆

**Comment by don1138** [comment]
I've added localization to [version 1.4.9](https://github.com/don1138/blender-qmm/releases/tag/v1.4.9).

Please test it and let me know if it works

**Comment by chenpaner** [comment]
![Snipaste_2022-10-18_10-24-37](https://user-images.githubusercontent.com/107256886/196320975-045216c4-f122-410c-a42d-3896c36d032f.png)
hi, the translation doesn't seem to work, can you tell me how to set it up?

**Comment by chenpaner** [comment]
![Snipaste_2022-10-18_10-48-55](https://user-images.githubusercontent.com/107256886/196324635-8e57d38f-c88d-4fd7-93a1-cb0ac4ab8cc8.png)
Sorry, I don't know how to put requirements under your qmc plugin. Can you add an RGB node instead of modifying the BSDF Shader, because in actual work, many copied materials do not contain the BSDF Shader

**Comment by don1138** [comment]
Okay, I've updated the [version 1.4.9](https://github.com/don1138/blender-qmm/releases/tag/v1.4.9) zip.
Please download it again and give it a try. It should work now.

![Localized ZH](https://raw.githubusercontent.com/don1138/blender-qmm/main/imx/localized-zh.jpg)

RE: Your **Quick Material Colors** suggestion: I opened Issues and [copy, pasted it -- and a solution -- there.](https://github.com/don1138/blender-qmc/issues/1).

**Comment by chenpaner** [comment]
Thanks！It‘s working！

**Comment by don1138** [comment]
Brilliant! Thanks for motivating me to learn how to localize/internationalize my add-ons.

**Comment by schroef** [comment]
I think using icons actually will allow for smaller menu. You can set the size for the preview thumbs. Perhaps i can code an example

**Comment by don1138** [comment]
> I think using icons actually will allow for smaller menu. You can set the size for the preview thumbs. Perhaps i can code an example

The problem I have with thumbnails is that in order to distinguish the materials properly, the thumbs need to be much bigger than 32x32 pixels -- probably at least twice that size -- and I want to keep the menu very compact.

I'm satisfied with using text labels only, but if you want to pitch an alternative using thumbnails, I'd be glad to take a look.

**Comment by schroef** [comment]
Ill check what i can come up with. I know we can alter the preview. you could try template_icon_view, but it needs materials for that. We could add a folder with material previews and use those.
If the icons are placed in subfolder per categorie, we can use an enum menu to show categories. Changing this menu will then show the icons per material
Here's a quick preview using materials, we can adjust the thumbnail icon size. An image says more than words ;)
![template_icon_view](https://user-images.githubusercontent.com/6923008/198859155-4207dc0b-bbf2-4e7a-b65b-106515e46fbd.png)
