### ISSUE TITLE
Questions)   When you want to use a different material by slightly changing the color of A teach me how to

### ISSUE THREAD

**Issue by gkcc0625** [don1138/blender-qmm#3]
I want to use it differently by slightly changing the color of the material of A.
If you try to apply it differently to the sphere on the right,
  The material and color of A change as well.

Questions)
What if, after duplicating the color of A, you want to use a different material by changing the color slightly?
I would be very grateful if you could teach me how

![Screenshot_26](https://user-images.githubusercontent.com/79390219/197126025-993c76cc-3c95-456b-ad12-85fd87d582f8.png)

**Comment by don1138** [comment]
This is the kind of question you should post to [Discord](https://discord.com/channels/185590609631903755/869803716390289488) or [Blender Artists](https://blenderartists.org/c/support/materials-and-textures/38) or can learn from a YouTube video like [How to copy materials in blender](https://www.youtube.com/watch?v=260D8ELBYGg).

But if I understand your question, then the short answer is to click the New Material icon in the Shader editor. Bam -- New material!

![New Material](https://raw.githubusercontent.com/don1138/imx/main/issues/new_material.png)

**Comment by gkcc0625** [comment]
Thank you very much for replying...

**Comment by don1138** [comment]
Glad to help!
